import React, { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Calendar, ChevronDown, TrendingDown, TrendingUp, Users, Wallet } from "lucide-react";
import { fetchMembers, PLAN_LABELS, ADMISSION_TYPE_LABELS } from "../../redux/slices/membersSlice";

const AGE_GROUPS = [
  { key: "15-25", label: "15-25", min: 15, max: 25 },
  { key: "26-35", label: "26-35", min: 26, max: 35 },
  { key: "36-50", label: "36-50", min: 36, max: 50 },
  { key: "50+", label: "50+", min: 51, max: Infinity },
];
const CHART_COLORS = ["#38bdf8", "#34d399", "#fbbf24", "#fb7185", "#a78bfa"];
const GENDER_COLORS = { Male: "#38bdf8", Female: "#f472b6", Other: "#fbbf24", Unknown: "#64748b" };
const PAYMENT_MODE_LABELS = { upi: "UPI", cash: "Cash", both: "Cash + UPI (old)" };
const PAYMENT_MODE_COLORS = { upi: "#38bdf8", cash: "#34d399", both: "#a78bfa" };

function formatDate(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function monthRange(offset = 0) { const date = new Date(); const start = new Date(date.getFullYear(), date.getMonth() + offset, 1); const end = new Date(date.getFullYear(), date.getMonth() + offset + 1, 0); return { fromDate: formatDate(start), toDate: formatDate(end) }; }
function fiscalRange(offset = 0) { const date = new Date(); const year = date.getFullYear() - (date.getMonth() < 3 ? 1 : 0) + offset; return { fromDate: `${year}-04-01`, toDate: `${year + 1}-03-31` }; }
function getPreviousRange(range) { if (!range.fromDate || !range.toDate) return { fromDate: "", toDate: "" }; const from = new Date(`${range.fromDate}T00:00:00`); const to = new Date(`${range.toDate}T00:00:00`); const days = Math.round((to - from) / 86400000) + 1; const previousTo = new Date(from); previousTo.setDate(previousTo.getDate() - 1); const previousFrom = new Date(previousTo); previousFrom.setDate(previousFrom.getDate() - days + 1); return { fromDate: formatDate(previousFrom), toDate: formatDate(previousTo) }; }
function groupEntries(entries, getKey, labels = {}) { const grouped = {}; entries.forEach((entry) => { const key = getKey(entry); if (!grouped[key]) grouped[key] = { key, label: labels[key] || key, amount: 0, count: 0 }; grouped[key].amount += entry.amount; grouped[key].count += 1; }); return Object.values(grouped).sort((a, b) => b.amount - a.amount); }

function Comparison({ value, previous }) { const change = previous ? ((value - previous) / previous) * 100 : value ? 100 : 0; const positive = change >= 0; const Icon = positive ? TrendingUp : TrendingDown; return <span className={`inline-flex items-center gap-1 text-xs font-semibold ${positive ? "text-emerald-400" : "text-rose-400"}`}><Icon size={13} /> {positive ? "+" : ""}{change.toFixed(1)}% vs last</span>; }

function ColumnChart({ data }) { const max = Math.max(...data.map((item) => item.amount), 1); return <div className="flex h-56 items-end gap-3 border-b border-slate-700 px-2 pb-2 pt-6">{data.map((item, index) => <div key={item.key} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] text-slate-400">₹{item.amount.toLocaleString("en-IN")}</span><div className="flex h-40 w-full items-end justify-center"><div className="w-full max-w-12 rounded-t-md transition-all duration-500" style={{ height: `${(item.amount / max) * 100}%`, background: CHART_COLORS[index % CHART_COLORS.length] }} /></div><span className="max-w-full truncate text-[11px] text-slate-300">{item.label}</span></div>)}</div>; }

function GenderPie({ data }) { const total = data.reduce((sum, item) => sum + item.amount, 0); let cursor = 0; const slices = data.map((item) => { const start = cursor; cursor += total ? (item.amount / total) * 360 : 0; return `${GENDER_COLORS[item.label] || GENDER_COLORS.Unknown} ${start}deg ${cursor}deg`; }); return <div className="flex flex-col items-center gap-5 sm:flex-row sm:justify-center"><div className="h-40 w-40 rounded-full" style={{ background: total ? `conic-gradient(${slices.join(",")})` : "#1e293b" }} /><div className="space-y-3">{data.map((item) => <div key={item.key} className="flex items-center gap-2 text-sm text-slate-300"><span className="h-3 w-3 rounded-full" style={{ background: GENDER_COLORS[item.label] || GENDER_COLORS.Unknown }} /><span>{item.label}</span><strong className="text-slate-100">₹{item.amount.toLocaleString("en-IN")}</strong></div>)}</div></div>; }

export default function Sales() {
  const dispatch = useDispatch();
  const members = useSelector((state) => state.members.members);
  const membersLoading = useSelector((state) => state.members.loading);
  const [datePreset, setDatePreset] = useState("current-month");
  const [customFrom, setCustomFrom] = useState("");
  const [customTo, setCustomTo] = useState("");
  const [chartFilter, setChartFilter] = useState("plan");
  useEffect(() => {
    if (members.length === 0 && !membersLoading) dispatch(fetchMembers());
  }, [dispatch, members.length, membersLoading]);
  const activeRange = useMemo(() => { if (datePreset === "current-month") return monthRange(); if (datePreset === "last-month") return monthRange(-1); if (datePreset === "current-fiscal") return fiscalRange(); if (datePreset === "last-fiscal") return fiscalRange(-1); return { fromDate: customFrom, toDate: customTo }; }, [datePreset, customFrom, customTo]);
  const previousRange = useMemo(() => getPreviousRange(activeRange), [activeRange]);
  const allEntries = useMemo(() => members.flatMap((member) => (member.membershipHistory || []).map((history) => ({ amount: Number(history.amount || 0), date: history.date, plan: history.plan || "unknown", age: Number(history.age ?? member.age), gender: history.gender || member.gender || "Unknown", paymentMode: history.paymentMode || "upi", admissionType: history.admissionType || "normal" }))), [members]);
  const inRange = (range) => allEntries.filter((entry) => entry.date && (!range.fromDate || entry.date >= range.fromDate) && (!range.toDate || entry.date <= range.toDate));
  const incomeEntries = useMemo(() => inRange(activeRange), [allEntries, activeRange]);
  const previousEntries = useMemo(() => inRange(previousRange), [allEntries, previousRange]);
  const totalIncome = incomeEntries.reduce((sum, entry) => sum + entry.amount, 0);
  const previousIncome = previousEntries.reduce((sum, entry) => sum + entry.amount, 0);
  const planIncome = useMemo(() => groupEntries(incomeEntries, (entry) => entry.plan, PLAN_LABELS), [incomeEntries]);
  const previousPlanIncome = useMemo(() => groupEntries(previousEntries, (entry) => entry.plan, PLAN_LABELS), [previousEntries]);
  const ageIncome = useMemo(() => AGE_GROUPS.map((group) => { const rows = incomeEntries.filter((entry) => entry.age >= group.min && entry.age <= group.max); return { ...group, amount: rows.reduce((sum, entry) => sum + entry.amount, 0), count: rows.length }; }), [incomeEntries]);
  const previousAgeIncome = useMemo(() => AGE_GROUPS.map((group) => { const rows = previousEntries.filter((entry) => entry.age >= group.min && entry.age <= group.max); return { ...group, amount: rows.reduce((sum, entry) => sum + entry.amount, 0), count: rows.length }; }), [previousEntries]);
  const genderIncome = useMemo(() => groupEntries(incomeEntries, (entry) => ["Male", "Female"].includes(entry.gender) ? entry.gender : "Other"), [incomeEntries]);
  const previousGenderIncome = useMemo(() => groupEntries(previousEntries, (entry) => ["Male", "Female"].includes(entry.gender) ? entry.gender : "Other"), [previousEntries]);
  const paymentModeIncome = useMemo(() => groupEntries(incomeEntries, (entry) => entry.paymentMode, PAYMENT_MODE_LABELS), [incomeEntries]);
  const previousPaymentModeIncome = useMemo(() => groupEntries(previousEntries, (entry) => entry.paymentMode, PAYMENT_MODE_LABELS), [previousEntries]);
  // Offer vs Normal admissions — count + amount for the selected period.
  const admissionTypeIncome = useMemo(() => groupEntries(incomeEntries, (entry) => entry.admissionType, ADMISSION_TYPE_LABELS), [incomeEntries]);
  const previousAdmissionTypeIncome = useMemo(() => groupEntries(previousEntries, (entry) => entry.admissionType, ADMISSION_TYPE_LABELS), [previousEntries]);
  const offerIncome = admissionTypeIncome.find((item) => item.key === "offer") || { amount: 0, count: 0 };
  const previousOfferIncome = previousAdmissionTypeIncome.find((item) => item.key === "offer") || { amount: 0, count: 0 };
  // "both" is a retired option — only show its tile if old entries
  // still carry it, so historical revenue never silently disappears.
  const hasLegacyBothMode = paymentModeIncome.some((item) => item.key === "both" && item.count > 0);
  const paymentModesToShow = hasLegacyBothMode ? ["upi", "cash", "both"] : ["upi", "cash"];
  const chartData = chartFilter === "plan" ? planIncome : chartFilter === "age" ? ageIncome : chartFilter === "mode" ? paymentModeIncome : chartFilter === "admission" ? admissionTypeIncome : genderIncome;
  const previousChartData = chartFilter === "plan" ? previousPlanIncome : chartFilter === "age" ? previousAgeIncome : chartFilter === "mode" ? previousPaymentModeIncome : chartFilter === "admission" ? previousAdmissionTypeIncome : previousGenderIncome;

  return <div className="min-h-screen bg-slate-950 px-3 pb-24 pt-4 text-slate-100 md:px-8 md:pb-8"><div className="mx-auto max-w-6xl"><div className="mb-6 border-b border-slate-800 pb-4"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-400">Revenue intelligence</p><h1 className="mt-1 text-2xl font-bold text-white md:text-3xl">Sales Overview</h1><p className="mt-1 text-sm text-slate-400">Compare collection performance across plan, age and gender.</p></div>
    <section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-xl md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><Wallet className="text-emerald-400" size={20} /><div><p className="text-xs uppercase tracking-wider text-slate-400">Total income</p><p className="text-3xl font-black text-white">₹{totalIncome.toLocaleString("en-IN")}</p></div></div><div className="flex w-full items-center gap-2 md:w-auto"><Calendar size={15} className="text-slate-400" /><select value={datePreset} onChange={(event) => setDatePreset(event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm text-slate-200 outline-none focus:border-cyan-400 md:w-64"><option value="current-month">Current Month</option><option value="last-month">Last Month</option><option value="current-fiscal">Current Financial Year</option><option value="last-fiscal">Last Financial Year</option><option value="custom">Custom Range</option></select></div></div>{datePreset === "custom" && <div className="mt-5 grid grid-cols-2 gap-3"><input type="date" value={customFrom} onChange={(event) => setCustomFrom(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm text-slate-200" /><input type="date" value={customTo} onChange={(event) => setCustomTo(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-sm text-slate-200" /></div>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-xs text-slate-500">Income vs previous period</p><Comparison value={totalIncome} previous={previousIncome} /></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-xs text-slate-500">Collection entries</p><p className="mt-1 text-lg font-bold">{incomeEntries.length} <span className="ml-1 text-xs font-normal text-slate-500">previous {previousEntries.length}</span></p><Comparison value={incomeEntries.length} previous={previousEntries.length} /></div><div className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-3"><p className="text-xs text-blue-400">Offer admissions</p><p className="mt-1 text-lg font-bold text-white">₹{offerIncome.amount.toLocaleString("en-IN")} <span className="ml-1 text-xs font-normal text-slate-500">{offerIncome.count} admission{offerIncome.count === 1 ? "" : "s"}</span></p><Comparison value={offerIncome.amount} previous={previousOfferIncome.amount} /></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-xs text-slate-500">Selected period</p><p className="mt-1 text-sm font-semibold text-slate-200">{activeRange.fromDate || "Any"} to {activeRange.toDate || "Any"}</p></div></div></section>
    <section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-xl md:p-6"><h2 className="mb-4 text-sm font-bold uppercase tracking-wider text-slate-500">UPI vs Cash</h2><div className={`grid grid-cols-1 gap-3 ${hasLegacyBothMode ? "sm:grid-cols-3" : "sm:grid-cols-2"}`}>{paymentModesToShow.map((mode) => { const row = paymentModeIncome.find((item) => item.key === mode) || { amount: 0, count: 0 }; const previous = previousPaymentModeIncome.find((item) => item.key === mode); return <div key={mode} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: PAYMENT_MODE_COLORS[mode] }} /><span className="text-xs font-semibold uppercase text-slate-400">{PAYMENT_MODE_LABELS[mode]}</span></div><p className="mt-2 text-2xl font-black text-white">₹{row.amount.toLocaleString("en-IN")}</p><p className="text-[11px] text-slate-500">{row.count} payment{row.count === 1 ? "" : "s"}</p><Comparison value={row.amount} previous={previous?.amount || 0} /></div>; })}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-xl md:p-6"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-white">Sales breakdown</h2><p className="text-xs text-slate-500">Total income by the selected dimension</p></div><div className="relative"><select value={chartFilter} onChange={(event) => setChartFilter(event.target.value)} className="appearance-none rounded-lg border border-slate-700 bg-slate-950 py-2 pl-3 pr-9 text-sm text-slate-200 outline-none focus:border-cyan-400"><option value="plan">Sales by Plan</option><option value="age">Sales by Age</option><option value="gender">Sales by Gender</option><option value="mode">Sales by Payment Mode</option><option value="admission">Sales by Admission Type</option></select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-2.5 text-slate-400" /></div></div>{membersLoading ? <div className="flex h-56 items-center justify-center text-sm text-slate-400">Loading sales data...</div> : chartFilter === "gender" ? <GenderPie data={genderIncome} /> : <ColumnChart data={chartData} />}{!membersLoading && chartFilter !== "gender" && <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{chartData.map((item, index) => { const previous = previousChartData.find((row) => row.key === item.key); return <div key={item.key} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: CHART_COLORS[index % CHART_COLORS.length] }} /><span className="truncate text-xs text-slate-400">{item.label}</span></div><p className="mt-1 font-bold">₹{item.amount.toLocaleString("en-IN")}</p><p className="text-[11px] text-slate-500">{item.count} entries</p><Comparison value={item.amount} previous={previous?.amount || 0} /></div>; })}</div>}{!membersLoading && chartFilter === "gender" && <div className="mt-5 grid grid-cols-2 gap-3">{genderIncome.map((item) => { const previous = previousGenderIncome.find((row) => row.key === item.key); return <div key={item.key} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-xs text-slate-400">{item.label}</p><p className="font-bold">₹{item.amount.toLocaleString("en-IN")}</p><Comparison value={item.amount} previous={previous?.amount || 0} /></div>; })}</div>}{!membersLoading && chartFilter === "gender" && <p className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Users size={14} /> Gender distribution is calculated from each sale entry.</p>}</section>
  </div></div>;
}